# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SaveForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(412, 179)
        Form.setStyleSheet("")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 161))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"  color: #333333;\n"
"  background-color: #e0e0e0;\n"
"  border-radius: 5px;\n"
"  font-weight: bold;\n"
"  font-size: 12px;\n"
"}\n"
"\n"
"QGroupBox > * {\n"
"  color: #333333;\n"
"  background-color: transparent;\n"
"}")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.seoInput_name = QtWidgets.QCheckBox(self.groupBox)
        self.seoInput_name.setGeometry(QtCore.QRect(230, 30, 141, 20))
        self.seoInput_name.setStyleSheet("QCheckBox {\n"
"  border-radius: 5px;\n"
"  background-color: #e0e0e0;\n"
"  border: 1px solid #2d9cdb;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"  color: #fff;\n"
"  background-color: #2f80ed;\n"
"}\n"
"\n"
"QCheckBox:disabled {\n"
"  color: #828282;\n"
"  background-color: #bdbdbd;\n"
"  border: none;\n"
"}")
        self.seoInput_name.setChecked(True)
        self.seoInput_name.setObjectName("seoInput_name")
        self.checkMD5_code = QtWidgets.QCheckBox(self.groupBox)
        self.checkMD5_code.setGeometry(QtCore.QRect(20, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkMD5_code.setFont(font)
        self.checkMD5_code.setStyleSheet("QCheckBox {\n"
"  border-radius: 5px;\n"
"  background-color: #e0e0e0;\n"
"  border: 1px solid #2d9cdb;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"  color: #fff;\n"
"  background-color: #2f80ed;\n"
"}\n"
"\n"
"QCheckBox:disabled {\n"
"  color: #828282;\n"
"  background-color: #bdbdbd;\n"
"  border: none;\n"
"}")
        self.checkMD5_code.setChecked(True)
        self.checkMD5_code.setObjectName("checkMD5_code")
        self.pixel500 = QtWidgets.QRadioButton(self.groupBox)
        self.pixel500.setGeometry(QtCore.QRect(20, 70, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pixel500.setFont(font)
        self.pixel500.setStyleSheet("QRadioButton {\n"
"  border-radius: 5px;\n"
"  background-color: #e0e0e0;\n"
"  border: 1px solid #2d9cdb;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"  color: #fff;\n"
"  background-color: #2f80ed;\n"
"}\n"
"\n"
"QRadioButton:disabled {\n"
"  color: #828282;\n"
"  background-color: #bdbdbd;\n"
"  border: none;\n"
"}")
        self.pixel500.setChecked(True)
        self.pixel500.setObjectName("pixel500")
        self.pixel720 = QtWidgets.QRadioButton(self.groupBox)
        self.pixel720.setGeometry(QtCore.QRect(140, 70, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pixel720.setFont(font)
        self.pixel720.setStyleSheet("QRadioButton {\n"
"  border-radius: 5px;\n"
"  background-color: #e0e0e0;\n"
"  border: 1px solid #2d9cdb;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"  color: #fff;\n"
"  background-color: #2f80ed;\n"
"}\n"
"\n"
"QRadioButton:disabled {\n"
"  color: #828282;\n"
"  background-color: #bdbdbd;\n"
"  border: none;\n"
"}")
        self.pixel720.setObjectName("pixel720")
        self.pixel1000 = QtWidgets.QRadioButton(self.groupBox)
        self.pixel1000.setGeometry(QtCore.QRect(260, 70, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pixel1000.setFont(font)
        self.pixel1000.setStyleSheet("QRadioButton {\n"
"  border-radius: 5px;\n"
"  background-color: #e0e0e0;\n"
"  border: 1px solid #2d9cdb;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"  color: #fff;\n"
"  background-color: #2f80ed;\n"
"}\n"
"\n"
"QRadioButton:disabled {\n"
"  color: #828282;\n"
"  background-color: #bdbdbd;\n"
"  border: none;\n"
"}")
        self.pixel1000.setObjectName("pixel1000")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(20, 100, 341, 1))
        self.line_2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.choosePath_save = QtWidgets.QPushButton(self.groupBox)
        self.choosePath_save.setGeometry(QtCore.QRect(130, 120, 131, 31))
        self.choosePath_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choosePath_save.setStyleSheet("QPushButton {\n"
"  border: 1px solid #2d9cdb;\n"
"  padding: 4px;\n"
"  border-radius: 2px;\n"
"  background-color: transparent;\n"
"  color: #333333;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  color: #fff;\n"
"  background-color: #2f80ed;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"  color: #828282;\n"
"  background-color: #bdbdbd;\n"
"  border: none;\n"
"}\n"
"\n"
"QMessageBox QPushButton {\n"
"  padding: 5px 20px;\n"
"}\n"
"")
        self.choosePath_save.setObjectName("choosePath_save")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Save From..."))
        self.seoInput_name.setText(_translate("Form", "Seo by Input Name"))
        self.checkMD5_code.setText(_translate("Form", "Thay đổi MD5 Code"))
        self.pixel500.setText(_translate("Form", "500 x 500 px"))
        self.pixel720.setText(_translate("Form", "720 x 720 px"))
        self.pixel1000.setText(_translate("Form", "1000 x 1000 px"))
        self.choosePath_save.setToolTip(_translate("Form", "<html><head/><body><p>All changes are undone and the first image is restored.</p></body></html>"))
        self.choosePath_save.setText(_translate("Form", "Lưu Với Lựa Chọn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
